import { NextRequest, NextResponse } from 'next/server';
import { writeFile, mkdir } from 'fs/promises';
import path from 'path';

// Blended action with percentages
interface BlendedAction {
  raise?: number;
  call?: number;
  fold?: number;
}

type HandAction = 'raise' | 'call' | 'fold' | BlendedAction;

interface SaveRangeRequest {
  stackSize: string;
  position: string;
  scenario: string;
  opponent?: string; // Optional for non-RFI scenarios
  data: Record<string, HandAction>;
  description?: string; // Strategy explanation for this range
}

/**
 * Formats a hand action for TypeScript output.
 * Simple actions become quoted strings, blended actions become object literals.
 */
function formatAction(action: HandAction): string {
  if (typeof action === 'string') {
    return `'${action}'`;
  }
  // Blended action - format as object
  const parts: string[] = [];
  if (action.raise !== undefined && action.raise > 0) {
    parts.push(`raise: ${action.raise}`);
  }
  if (action.call !== undefined && action.call > 0) {
    parts.push(`call: ${action.call}`);
  }
  if (action.fold !== undefined && action.fold > 0) {
    parts.push(`fold: ${action.fold}`);
  }
  return `{ ${parts.join(', ')} }`;
}

/**
 * Generates the TypeScript file content for a poker range.
 */
function generateRangeFileContent(
  stackSize: string,
  position: string,
  scenario: string,
  opponent: string | undefined,
  data: Record<string, HandAction>,
  description?: string
): string {
  // Build variable name
  let variableName = `${position.toLowerCase().replace('+', 'Plus')}`;
  if (opponent && scenario !== 'rfi') {
    variableName += `Vs${opponent.replace('+', 'Plus')}`;
  }
  variableName += `${stackSize}${scenario.charAt(0).toUpperCase() + scenario.slice(1).replace('-', '')}`;
  
  const displayName = getDisplayName(stackSize, position, scenario, opponent);

  const dataEntries = Object.entries(data)
    .map(([hand, action]) => `  '${hand}': ${formatAction(action)},`)
    .join('\n');

  // Build meta object with optional opponentPosition and description
  const metaLines = [
    `    stackSize: '${stackSize}',`,
    `    position: '${position}',`,
    `    scenario: '${scenario}',`,
  ];
  
  if (opponent && scenario !== 'rfi') {
    metaLines.push(`    opponentPosition: '${opponent}',`);
  }
  
  metaLines.push(`    displayName: '${displayName}',`);
  
  if (description) {
    // Escape single quotes and newlines in description
    const escapedDescription = description.replace(/'/g, "\\'").replace(/\n/g, '\\n');
    metaLines.push(`    description: '${escapedDescription}',`);
  }

  return `import type { PokerRange, RangeData } from '@/types';

/**
 * ${displayName}
 * Generated by Chart Topper Builder
 */

const data: RangeData = {
${dataEntries}
};

export const ${variableName}: PokerRange = {
  meta: {
${metaLines.join('\n')}
  },
  data,
};

export default ${variableName};
`;
}

function getDisplayName(stackSize: string, position: string, scenario: string, opponent?: string): string {
  const scenarioNames: Record<string, string> = {
    'rfi': 'Raise First In',
    'vs-raise': 'vs Raise',
    'vs-3bet': 'vs 3-Bet',
  };
  
  if (opponent && scenario !== 'rfi') {
    return `${stackSize}+ ${position} vs ${opponent} - ${scenarioNames[scenario] || scenario}`;
  }
  
  return `${stackSize}+ ${position} - ${scenarioNames[scenario] || scenario}`;
}

export async function POST(request: NextRequest) {
  try {
    const body: SaveRangeRequest = await request.json();
    const { stackSize, position, scenario, opponent, data, description } = body;

    // Validate required fields
    if (!stackSize || !position || !scenario || !data) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Validate all 169 hands are present
    const handCount = Object.keys(data).length;
    if (handCount !== 169) {
      return NextResponse.json(
        { error: `Expected 169 hands, got ${handCount}` },
        { status: 400 }
      );
    }

    // Generate filename based on whether opponent is present
    const positionSlug = position.toLowerCase().replace('+', 'plus');
    let filename: string;
    
    if (opponent && scenario !== 'rfi') {
      const opponentSlug = opponent.toLowerCase().replace('+', 'plus');
      filename = `${stackSize}-${positionSlug}-vs-${opponentSlug}-${scenario}.ts`;
    } else {
      filename = `${stackSize}-${positionSlug}-${scenario}.ts`;
    }
    
    const rangesDir = path.join(process.cwd(), 'data', 'ranges');
    const filepath = path.join(rangesDir, filename);

    // Ensure directory exists
    await mkdir(rangesDir, { recursive: true });

    // Generate file content
    const content = generateRangeFileContent(stackSize, position, scenario, opponent, data, description);

    // Write file
    await writeFile(filepath, content, 'utf-8');

    return NextResponse.json({
      success: true,
      filename,
      filepath: `data/ranges/${filename}`,
    });
  } catch (error) {
    console.error('Error saving range:', error);
    return NextResponse.json(
      { error: 'Failed to save range' },
      { status: 500 }
    );
  }
}
