import { NextRequest, NextResponse } from 'next/server';
import { writeFile, mkdir } from 'fs/promises';
import path from 'path';

interface SaveRangeRequest {
  stackSize: string;
  position: string;
  scenario: string;
  data: Record<string, 'raise' | 'call' | 'fold'>;
}

/**
 * Generates the TypeScript file content for a poker range.
 */
function generateRangeFileContent(
  stackSize: string,
  position: string,
  scenario: string,
  data: Record<string, string>
): string {
  const variableName = `${position.toLowerCase().replace('+', 'Plus')}${stackSize}${scenario.charAt(0).toUpperCase() + scenario.slice(1).replace('-', '')}`;
  const displayName = getDisplayName(stackSize, position, scenario);

  const dataEntries = Object.entries(data)
    .map(([hand, action]) => `  '${hand}': '${action}',`)
    .join('\n');

  return `import type { PokerRange, RangeData } from '@/types';

/**
 * ${displayName}
 * Generated by Chart Topper Builder
 */

const data: RangeData = {
${dataEntries}
};

export const ${variableName}: PokerRange = {
  meta: {
    stackSize: '${stackSize}',
    position: '${position}',
    scenario: '${scenario}',
    displayName: '${displayName}',
  },
  data,
};

export default ${variableName};
`;
}

function getDisplayName(stackSize: string, position: string, scenario: string): string {
  const scenarioNames: Record<string, string> = {
    'rfi': 'Raise First In',
    'vs-raise': 'vs Raise',
    'vs-3bet': 'vs 3-Bet',
  };
  
  return `${stackSize}+ ${position} - ${scenarioNames[scenario] || scenario}`;
}

export async function POST(request: NextRequest) {
  try {
    const body: SaveRangeRequest = await request.json();
    const { stackSize, position, scenario, data } = body;

    // Validate required fields
    if (!stackSize || !position || !scenario || !data) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Validate all 169 hands are present
    const handCount = Object.keys(data).length;
    if (handCount !== 169) {
      return NextResponse.json(
        { error: `Expected 169 hands, got ${handCount}` },
        { status: 400 }
      );
    }

    // Generate filename
    const filename = `${stackSize}-${position.toLowerCase().replace('+', 'plus')}-${scenario}.ts`;
    const rangesDir = path.join(process.cwd(), 'data', 'ranges');
    const filepath = path.join(rangesDir, filename);

    // Ensure directory exists
    await mkdir(rangesDir, { recursive: true });

    // Generate file content
    const content = generateRangeFileContent(stackSize, position, scenario, data);

    // Write file
    await writeFile(filepath, content, 'utf-8');

    return NextResponse.json({
      success: true,
      filename,
      filepath: `data/ranges/${filename}`,
    });
  } catch (error) {
    console.error('Error saving range:', error);
    return NextResponse.json(
      { error: 'Failed to save range' },
      { status: 500 }
    );
  }
}
